// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: clients.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createClient = `-- name: CreateClient :one
INSERT INTO clients (id, name, status)
VALUES ($1, $2, $3)
RETURNING id, name, status, created_at, updated_at
`

type CreateClientParams struct {
	ID     uuid.UUID
	Name   string
	Status string
}

func (q *Queries) CreateClient(ctx context.Context, arg CreateClientParams) (Client, error) {
	row := q.db.QueryRow(ctx, createClient, arg.ID, arg.Name, arg.Status)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateClient = `-- name: DeactivateClient :one
UPDATE clients
SET status = 'inactive', updated_at = now()
WHERE id = $1
RETURNING id, name, status, created_at, updated_at
`

func (q *Queries) DeactivateClient(ctx context.Context, id uuid.UUID) (Client, error) {
	row := q.db.QueryRow(ctx, deactivateClient, id)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getClient = `-- name: GetClient :one
SELECT id, name, status, created_at, updated_at FROM clients WHERE id = $1
`

func (q *Queries) GetClient(ctx context.Context, id uuid.UUID) (Client, error) {
	row := q.db.QueryRow(ctx, getClient, id)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getClientForUpdate = `-- name: GetClientForUpdate :one
SELECT id, name, status, created_at, updated_at FROM clients WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetClientForUpdate(ctx context.Context, id uuid.UUID) (Client, error) {
	row := q.db.QueryRow(ctx, getClientForUpdate, id)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listClients = `-- name: ListClients :many
SELECT id, name, status, created_at, updated_at FROM clients
WHERE (status = $1 OR $1 IS NULL)
ORDER BY created_at DESC, id DESC
LIMIT $3 OFFSET $2
`

type ListClientsParams struct {
	Status pgtype.Text
	Offset int32
	Limit  int32
}

func (q *Queries) ListClients(ctx context.Context, arg ListClientsParams) ([]Client, error) {
	rows, err := q.db.Query(ctx, listClients, arg.Status, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Client
	for rows.Next() {
		var i Client
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateClient = `-- name: UpdateClient :one
UPDATE clients
SET name = $2, status = $3, updated_at = now()
WHERE id = $1
RETURNING id, name, status, created_at, updated_at
`

type UpdateClientParams struct {
	ID     uuid.UUID
	Name   string
	Status string
}

func (q *Queries) UpdateClient(ctx context.Context, arg UpdateClientParams) (Client, error) {
	row := q.db.QueryRow(ctx, updateClient, arg.ID, arg.Name, arg.Status)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
