// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rate_rules.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createRateRule = `-- name: CreateRateRule :one
INSERT INTO rate_rules (id, client_id, api, requests_allowed, window_seconds)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, client_id, api, requests_allowed, window_seconds, created_at, updated_at
`

type CreateRateRuleParams struct {
	ID              uuid.UUID
	ClientID        pgtype.UUID
	Api             string
	RequestsAllowed int32
	WindowSeconds   int32
}

func (q *Queries) CreateRateRule(ctx context.Context, arg CreateRateRuleParams) (RateRule, error) {
	row := q.db.QueryRow(ctx, createRateRule,
		arg.ID,
		arg.ClientID,
		arg.Api,
		arg.RequestsAllowed,
		arg.WindowSeconds,
	)
	var i RateRule
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.Api,
		&i.RequestsAllowed,
		&i.WindowSeconds,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteRateRuleByClient = `-- name: DeleteRateRuleByClient :exec
DELETE FROM rate_rules WHERE id = $1 AND client_id = $2
`

type DeleteRateRuleByClientParams struct {
	ID       uuid.UUID
	ClientID pgtype.UUID
}

func (q *Queries) DeleteRateRuleByClient(ctx context.Context, arg DeleteRateRuleByClientParams) error {
	_, err := q.db.Exec(ctx, deleteRateRuleByClient, arg.ID, arg.ClientID)
	return err
}

const getRateRule = `-- name: GetRateRule :one
SELECT id, client_id, api, requests_allowed, window_seconds, created_at, updated_at FROM rate_rules WHERE id = $1
`

func (q *Queries) GetRateRule(ctx context.Context, id uuid.UUID) (RateRule, error) {
	row := q.db.QueryRow(ctx, getRateRule, id)
	var i RateRule
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.Api,
		&i.RequestsAllowed,
		&i.WindowSeconds,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRateRuleByClientAndAPI = `-- name: GetRateRuleByClientAndAPI :one
SELECT id, client_id, api, requests_allowed, window_seconds, created_at, updated_at FROM rate_rules
WHERE client_id = $1 AND api = $2
`

type GetRateRuleByClientAndAPIParams struct {
	ClientID pgtype.UUID
	Api      string
}

func (q *Queries) GetRateRuleByClientAndAPI(ctx context.Context, arg GetRateRuleByClientAndAPIParams) (RateRule, error) {
	row := q.db.QueryRow(ctx, getRateRuleByClientAndAPI, arg.ClientID, arg.Api)
	var i RateRule
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.Api,
		&i.RequestsAllowed,
		&i.WindowSeconds,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRateRuleForUpdate = `-- name: GetRateRuleForUpdate :one
SELECT id, client_id, api, requests_allowed, window_seconds, created_at, updated_at FROM rate_rules WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetRateRuleForUpdate(ctx context.Context, id uuid.UUID) (RateRule, error) {
	row := q.db.QueryRow(ctx, getRateRuleForUpdate, id)
	var i RateRule
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.Api,
		&i.RequestsAllowed,
		&i.WindowSeconds,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRateRules = `-- name: ListRateRules :many
SELECT id, client_id, api, requests_allowed, window_seconds, created_at, updated_at FROM rate_rules
WHERE (client_id = $1 OR $1 IS NULL)
  AND (api = $2 OR $2 IS NULL)
ORDER BY created_at DESC, id DESC
LIMIT $4 OFFSET $3
`

type ListRateRulesParams struct {
	ClientID pgtype.UUID
	Api      pgtype.Text
	Offset   int32
	Limit    int32
}

func (q *Queries) ListRateRules(ctx context.Context, arg ListRateRulesParams) ([]RateRule, error) {
	rows, err := q.db.Query(ctx, listRateRules,
		arg.ClientID,
		arg.Api,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RateRule
	for rows.Next() {
		var i RateRule
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.Api,
			&i.RequestsAllowed,
			&i.WindowSeconds,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRateRulesByClient = `-- name: ListRateRulesByClient :many
SELECT id, client_id, api, requests_allowed, window_seconds, created_at, updated_at FROM rate_rules
WHERE client_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListRateRulesByClient(ctx context.Context, clientID pgtype.UUID) ([]RateRule, error) {
	rows, err := q.db.Query(ctx, listRateRulesByClient, clientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RateRule
	for rows.Next() {
		var i RateRule
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.Api,
			&i.RequestsAllowed,
			&i.WindowSeconds,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRateRule = `-- name: UpdateRateRule :one
UPDATE rate_rules
SET requests_allowed = $2, window_seconds = $3, updated_at = now()
WHERE id = $1
RETURNING id, client_id, api, requests_allowed, window_seconds, created_at, updated_at
`

type UpdateRateRuleParams struct {
	ID              uuid.UUID
	RequestsAllowed int32
	WindowSeconds   int32
}

func (q *Queries) UpdateRateRule(ctx context.Context, arg UpdateRateRuleParams) (RateRule, error) {
	row := q.db.QueryRow(ctx, updateRateRule, arg.ID, arg.RequestsAllowed, arg.WindowSeconds)
	var i RateRule
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.Api,
		&i.RequestsAllowed,
		&i.WindowSeconds,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
